import { ContentRegistryItem } from './types';

export const MINDFULNESS_REGISTRY: ContentRegistryItem[] = [
  // Anxious
  {
    id: 'anxious_1',
    emotion: 'anxious',
    theme: 'Patience and Prayer',
    quranReference: { surahNumber: 2, ayahNumber: 153, translation: 'Seek comfort in patience and prayer. Allah is truly with those who are patient', surahName: 'Al-Baqarah' },
    quranTextShort: 'Seek comfort in patience and prayer.',
    reflection: 'It sounds like your heart feels unsettled right now.',
    sunnahType: null,
    actionPrompt: 'take one slow breath, then say one short dua for ease',
    followUpQuestion: 'Would you like a dua, a verse reflection, or a 60-second calming pause?',
    quickReplies: ['A dua', 'Verse reflection', 'Calming pause'],
    escalationType: 'none',
    confidence: 'high',
    scholarReviewStatus: true,
    fullResponseText: 'It sounds like your heart feels unsettled right now. A relevant Qur’anic reminder is: ‘Seek comfort in patience and prayer. Allah is truly with those who are patient’ (2:153). One step now: take one slow breath, then say one short dua for ease. Would you like a dua, a verse reflection, or a 60-second calming pause?'
  },
  {
    id: 'anxious_2',
    emotion: 'anxious',
    theme: 'Comfort in Remembrance',
    quranReference: { surahNumber: 13, ayahNumber: 28, translation: 'Hearts find comfort in His remembrance', surahName: 'Ar-Ra\'d' },
    quranTextShort: 'Hearts find comfort in His remembrance',
    reflection: 'You do not need to solve everything in this minute.',
    sunnahType: null,
    actionPrompt: 'Try repeating a simple remembrance softly for one minute.',
    followUpQuestion: 'Do you want remembrance, breathing, or a short reflection?',
    quickReplies: ['Remembrance', 'Breathing', 'Short reflection'],
    escalationType: 'none',
    confidence: 'high',
    scholarReviewStatus: true,
    fullResponseText: 'You do not need to solve everything in this minute. Allah says that hearts find comfort in His remembrance, so let this moment become smaller through dhikr. Try repeating a simple remembrance softly for one minute. Do you want remembrance, breathing, or a short reflection?'
  },
  {
    id: 'anxious_3',
    emotion: 'anxious',
    theme: 'Prophetic Supplication for Distress',
    quranReference: { surahNumber: 0, ayahNumber: 0, translation: '', surahName: '' }, // Handled via Sunnah
    quranTextShort: '',
    reflection: 'A Prophetic supplication reported for distress begins: ‘La ilaha ill-Allah Al-‘Azim Al-Halim…’',
    sunnahType: 'dua',
    sunnahReference: { type: 'dua', translation: 'La ilaha ill-Allah Al-‘Azim Al-Halim', source: 'Sahih Muslim' },
    actionPrompt: 'Start there, then pause your thoughts and loosen your shoulders.',
    followUpQuestion: 'Would you like the dua, transliteration, or just the meaning?',
    quickReplies: ['The dua', 'Transliteration', 'Meaning'],
    escalationType: 'none',
    confidence: 'high',
    scholarReviewStatus: true,
    fullResponseText: 'A Prophetic supplication reported for distress begins: ‘La ilaha ill-Allah Al-‘Azim Al-Halim…’ and was narrated in Sahih Muslim for moments of distress. Start there, then pause your thoughts and loosen your shoulders. Would you like the dua, transliteration, or just the meaning?'
  },
  
  // Restless
  {
    id: 'restless_1',
    emotion: 'restless',
    theme: 'Stillness and Dhikr',
    quranReference: { surahNumber: 13, ayahNumber: 28, translation: 'Hearts find comfort in the remembrance of Allah', surahName: 'Ar-Ra\'d' },
    quranTextShort: 'Hearts find comfort in the remembrance of Allah',
    reflection: 'Restlessness often feels like the body is asking for stillness before the mind is ready.',
    sunnahType: null,
    actionPrompt: 'Try sitting still for 30 seconds and repeating dhikr gently.',
    followUpQuestion: 'Do you need calm, focus, or reassurance?',
    quickReplies: ['Calm', 'Focus', 'Reassurance'],
    escalationType: 'none',
    confidence: 'high',
    scholarReviewStatus: true,
    fullResponseText: 'Restlessness often feels like the body is asking for stillness before the mind is ready. A relevant reminder is that hearts find comfort in the remembrance of Allah. Try sitting still for 30 seconds and repeating dhikr gently. Do you need calm, focus, or reassurance?'
  },
  {
    id: 'restless_2',
    emotion: 'restless',
    theme: 'Small acts of order',
    quranReference: { surahNumber: 0, ayahNumber: 0, translation: '', surahName: '' },
    quranTextShort: '',
    reflection: 'If your thoughts keep jumping, do one small act of order rather than forcing deep reflection.',
    sunnahType: 'practice',
    sunnahReference: { type: 'practice', translation: 'Wudu', source: 'Sunnah' },
    actionPrompt: 'Make wudu or sit quietly and begin with dhikr, then return to what matters.',
    followUpQuestion: 'Would you like a simple dhikr, a verse, or a reset routine?',
    quickReplies: ['Simple dhikr', 'A verse', 'Reset routine'],
    escalationType: 'none',
    confidence: 'high',
    scholarReviewStatus: true,
    fullResponseText: 'If your thoughts keep jumping, do one small act of order rather than forcing deep reflection. Make wudu or sit quietly and begin with dhikr, then return to what matters. Would you like a simple dhikr, a verse, or a reset routine?'
  },

  // Sad
  {
    id: 'sad_1',
    emotion: 'sad',
    theme: 'Patience and Divine Help',
    quranReference: { surahNumber: 2, ayahNumber: 153, translation: 'Believers seek help through patience and prayer, and Allah is with the patient', surahName: 'Al-Baqarah' },
    quranTextShort: 'Allah is with the patient',
    reflection: 'I’m sorry this feels heavy.',
    sunnahType: null,
    actionPrompt: 'Keep the next step small: sit, breathe, and ask Allah for relief.',
    followUpQuestion: 'Do you want comfort from a verse, a dua for sorrow, or space to write?',
    quickReplies: ['A verse', 'Dua for sorrow', 'Space to write'],
    escalationType: 'none',
    confidence: 'high',
    scholarReviewStatus: true,
    fullResponseText: 'I’m sorry this feels heavy. A relevant Qur’anic reminder is that believers seek help through patience and prayer, and Allah is with the patient. For now, keep the next step small: sit, breathe, and ask Allah for relief. Do you want comfort from a verse, a dua for sorrow, or space to write?'
  },
  {
    id: 'sad_2',
    emotion: 'sad',
    theme: 'Qur\'an as the Spring of the Heart',
    quranReference: { surahNumber: 0, ayahNumber: 0, translation: '', surahName: '' },
    quranTextShort: '',
    reflection: 'One reported supplication for anxiety and grief asks Allah to make the Qur’an the spring of the heart and a removal of sorrow.',
    sunnahType: 'dua',
    sunnahReference: { type: 'dua', translation: 'Make the Qur’an the spring of my heart', source: 'Ahmad' },
    actionPrompt: 'Begin with that dua and keep your reflection brief and honest.',
    followUpQuestion: 'Would you like the dua, a short explanation, or a journaling prompt?',
    quickReplies: ['The dua', 'Short explanation', 'Journaling prompt'],
    escalationType: 'none',
    confidence: 'high',
    scholarReviewStatus: true,
    fullResponseText: 'One reported supplication for anxiety and grief asks Allah to make the Qur’an the spring of the heart and a removal of sorrow. If you want, begin with that dua and keep your reflection brief and honest. Would you like the dua, a short explanation, or a journaling prompt?'
  },

  // Overwhelmed
  {
    id: 'overwhelmed_1',
    emotion: 'overwhelmed',
    theme: 'Focus on One Thing',
    quranReference: { surahNumber: 0, ayahNumber: 0, translation: '', surahName: '' },
    quranTextShort: '',
    reflection: 'When everything feels too much, do not carry all of it at once.',
    sunnahType: null,
    actionPrompt: 'Return to one act: patience, prayer, and a quieter heart. For the next minute, choose only one thing to place before Allah.',
    followUpQuestion: 'Would you like help slowing down, making dua, or organizing your thoughts?',
    quickReplies: ['Slowing down', 'Making dua', 'Organize thoughts'],
    escalationType: 'none',
    confidence: 'high',
    scholarReviewStatus: true,
    fullResponseText: 'When everything feels too much, do not carry all of it at once. Return to one act: patience, prayer, and a quieter heart. For the next minute, choose only one thing to place before Allah. Would you like help slowing down, making dua, or organizing your thoughts?'
  },
  {
    id: 'overwhelmed_2',
    emotion: 'overwhelmed',
    theme: 'Grounding in Remembrance',
    quranReference: { surahNumber: 13, ayahNumber: 28, translation: 'Hearts find comfort in His remembrance', surahName: 'Ar-Ra\'d' },
    quranTextShort: 'Hearts find comfort in His remembrance',
    reflection: 'Your mind may be asking for control when what you need first is grounding.',
    sunnahType: 'dhikr',
    sunnahReference: { type: 'dhikr', translation: 'Dhikr', source: 'Sunnah' },
    actionPrompt: 'Place your phone down for 30 seconds and repeat dhikr slowly.',
    followUpQuestion: 'Should we do a one-minute reset, a verse reflection, or a wrap-up?',
    quickReplies: ['1-minute reset', 'Verse reflection', 'Wrap-up'],
    escalationType: 'none',
    confidence: 'high',
    scholarReviewStatus: true,
    fullResponseText: 'Your mind may be asking for control when what you need first is grounding. Begin with remembrance, because Allah says hearts find comfort in His remembrance. Place your phone down for 30 seconds and repeat dhikr slowly. Should we do a one-minute reset, a verse reflection, or a wrap-up?'
  },

  // Guilty
  {
    id: 'guilty_1',
    emotion: 'guilty',
    theme: 'Sincere Return',
    quranReference: { surahNumber: 0, ayahNumber: 0, translation: '', surahName: '' },
    quranTextShort: '',
    reflection: 'Feeling guilty can be a door to sincere return if it leads to repentance and not despair.',
    sunnahType: null,
    actionPrompt: 'Bring the feeling to Allah honestly, ask forgiveness, and take one small corrective step today.',
    followUpQuestion: 'Do you want a repentance-focused reflection, a dua, or a next action?',
    quickReplies: ['Reflection', 'A dua', 'Next action'],
    escalationType: 'none',
    confidence: 'high',
    scholarReviewStatus: true,
    fullResponseText: 'Feeling guilty can be a door to sincere return if it leads to repentance and not despair. Bring the feeling to Allah honestly, ask forgiveness, and take one small corrective step today. Do you want a repentance-focused reflection, a dua, or a next action?'
  },
  {
    id: 'guilty_2',
    emotion: 'guilty',
    theme: 'Tawbah and Humility',
    quranReference: { surahNumber: 0, ayahNumber: 0, translation: '', surahName: '' },
    quranTextShort: '',
    reflection: 'Do not let guilt turn into paralysis. Let it become tawbah, humility, and one better choice now.',
    sunnahType: null,
    actionPrompt: 'Keep it simple: ask Allah’s forgiveness and choose one action that reflects sincerity.',
    followUpQuestion: 'Would you like help with words of repentance, a verse reminder, or a private journal prompt?',
    quickReplies: ['Words of repentance', 'Verse reminder', 'Journal prompt'],
    escalationType: 'none',
    confidence: 'high',
    scholarReviewStatus: true,
    fullResponseText: 'Do not let guilt turn into paralysis. Let it become tawbah, humility, and one better choice now. Keep it simple: ask Allah’s forgiveness and choose one action that reflects sincerity. Would you like help with words of repentance, a verse reminder, or a private journal prompt?'
  },

  // Angry
  {
    id: 'angry_1',
    emotion: 'angry',
    theme: 'Slowing Before Speaking',
    quranReference: { surahNumber: 0, ayahNumber: 0, translation: '', surahName: '' },
    quranTextShort: '',
    reflection: 'Anger needs slowing before speaking.',
    sunnahType: 'practice',
    sunnahReference: { type: 'practice', translation: 'Seek refuge in Allah', source: 'Sunnah' },
    actionPrompt: 'Move away from the trigger, lower your voice, and begin with remembrance of Allah before reacting.',
    followUpQuestion: 'Would you like a pause exercise, a brief reminder, or help drafting a calmer response?',
    quickReplies: ['Pause exercise', 'Brief reminder', 'Calmer response'],
    escalationType: 'none',
    confidence: 'high',
    scholarReviewStatus: true,
    fullResponseText: 'Anger needs slowing before speaking. Move away from the trigger, lower your voice, and begin with remembrance of Allah before reacting. Would you like a pause exercise, a brief reminder, or help drafting a calmer response?'
  },

  // Lonely
  {
    id: 'lonely_1',
    emotion: 'lonely',
    theme: 'Nearness to Allah',
    quranReference: { surahNumber: 0, ayahNumber: 0, translation: '', surahName: '' },
    quranTextShort: '',
    reflection: 'Loneliness can feel sharp, but it does not mean you are abandoned.',
    sunnahType: null,
    actionPrompt: 'Let this be a moment of nearness to Allah through remembrance, then one act of connection with a trusted person.',
    followUpQuestion: 'Do you want spiritual reassurance, a dua, or a practical next step?',
    quickReplies: ['Spiritual reassurance', 'A dua', 'Practical step'],
    escalationType: 'none',
    confidence: 'high',
    scholarReviewStatus: true,
    fullResponseText: 'Loneliness can feel sharp, but it does not mean you are abandoned. Let this be a moment of nearness to Allah through remembrance, then one act of connection with a trusted person. Do you want spiritual reassurance, a dua, or a practical next step?'
  },

  // Grateful
  {
    id: 'grateful_1',
    emotion: 'grateful',
    theme: 'Deepening Gratitude',
    quranReference: { surahNumber: 0, ayahNumber: 0, translation: '', surahName: '' },
    quranTextShort: '',
    reflection: 'That gratitude is a gift worth holding gently.',
    sunnahType: null,
    actionPrompt: 'Turn it into remembrance, a short note, or a dua of thanks so the moment deepens instead of passing quickly.',
    followUpQuestion: 'Would you like to write it, say it, or reflect on it?',
    quickReplies: ['Write it', 'Say it', 'Reflect on it'],
    escalationType: 'none',
    confidence: 'high',
    scholarReviewStatus: true,
    fullResponseText: 'That gratitude is a gift worth holding gently. Turn it into remembrance, a short note, or a dua of thanks so the moment deepens instead of passing quickly. Would you like to write it, say it, or reflect on it?'
  },
  {
    id: 'grateful_2',
    emotion: 'grateful',
    theme: 'Remembering the Giver',
    quranReference: { surahNumber: 0, ayahNumber: 0, translation: '', surahName: '' },
    quranTextShort: '',
    reflection: 'A grateful heart becomes steadier when it remembers the One who gave the blessing.',
    sunnahType: 'dhikr',
    sunnahReference: { type: 'dhikr', translation: 'Dhikr', source: 'Sunnah' },
    actionPrompt: 'Pause for a moment of dhikr, then name one blessing and one way to use it well.',
    followUpQuestion: 'Do you want a gratitude reflection, a dua, or a shareable note?',
    quickReplies: ['Gratitude reflection', 'A dua', 'Shareable note'],
    escalationType: 'none',
    confidence: 'high',
    scholarReviewStatus: true,
    fullResponseText: 'A grateful heart becomes steadier when it remembers the One who gave the blessing. Pause for a moment of dhikr, then name one blessing and one way to use it well. Do you want a gratitude reflection, a dua, or a shareable note?'
  }
];
