export const colors = {
    primary: '#059669', // Emerald 600
    primaryLight: '#34D399', // Emerald 400
    primaryDark: '#064E3B', // Emerald 900

    secondary: '#D97706', // Amber 600
    secondaryLight: '#FBBF24', // Amber 400

    background: '#F3F4F6', // Gray 100
    surface: '#FFFFFF',

    text: '#1F2937', // Gray 800
    textSecondary: '#6B7280', // Gray 500
    textLight: '#F9FAFB', // Gray 50
    textBody: '#374151', // Gray 700

    success: '#10B981',
    error: '#EF4444',
    border: '#E5E7EB',

    sg: {
        light: {
            surfaceDim: '#d0dbed',
            onTertiaryFixed: '#1c1c19',
            surfaceContainerHighest: '#d9e3f6',
            surface: '#f8f9ff',
            onSecondaryFixed: '#241a00',
            primaryContainer: '#064e3b',
            inversePrimary: '#95d3ba',
            surfaceBright: '#f8f9ff',
            tertiaryContainer: '#454441',
            surfaceVariant: '#d9e3f6',
            onSecondaryContainer: '#745c00',
            inverseOnSurface: '#eaf1ff',
            primary: '#003527',
            onPrimaryFixed: '#002117',
            secondary: '#735c00',
            background: '#f8f9ff',
            inverseSurface: '#27313f',
            onError: '#ffffff',
            surfaceContainerLowest: '#ffffff',
            onSurface: '#121c2a',
            onPrimaryFixedVariant: '#0b513d',
            tertiaryFixed: '#e5e2dd',
            surfaceContainer: '#e6eeff',
            surfaceContainerHigh: '#dee9fc',
            outline: '#707974',
            onSurfaceVariant: '#404944',
            onTertiaryFixedVariant: '#474743',
            onPrimary: '#ffffff',
            errorContainer: '#ffdad6',
            onSecondaryFixedVariant: '#574500',
            surfaceTint: '#2b6954',
            onTertiary: '#ffffff',
            secondaryFixed: '#ffe088',
            primaryFixedDim: '#95d3ba',
            secondaryContainer: '#fed65b',
            onTertiaryContainer: '#b3b1ad',
            onPrimaryContainer: '#80bea6',
            primaryFixed: '#b0f0d6',
            outlineVariant: '#bfc9c3',
            secondaryFixedDim: '#e9c349',
            tertiary: '#2e2e2b',
            onErrorContainer: '#93000a',
            onBackground: '#121c2a',
            tertiaryFixedDim: '#c9c6c2',
            onSecondary: '#ffffff',
            error: '#ba1a1a',
            surfaceContainerLow: '#eff4ff',
        },
        dark: {
            surface: '#0a141f',
            surfaceDim: '#0a141f',
            surfaceBright: '#303a46',
            surfaceContainerLowest: '#050f1a',
            surfaceContainerLow: '#131c28',
            surfaceContainer: '#17202c',
            surfaceContainerHigh: '#212b37',
            surfaceContainerHighest: '#2c3642',
            onSurface: '#d9e3f3',
            onSurfaceVariant: '#d0c5af',
            inverseSurface: '#d9e3f3',
            inverseOnSurface: '#27313d',
            outline: '#99907c',
            outlineVariant: '#4d4635',
            surfaceTint: '#e9c349',
            primary: '#f2ca50',
            onPrimary: '#3c2f00',
            primaryContainer: '#d4af37',
            onPrimaryContainer: '#554300',
            inversePrimary: '#735c00',
            secondary: '#68dbb3',
            onSecondary: '#003829',
            secondaryContainer: '#25a37f',
            onSecondaryContainer: '#003123',
            tertiary: '#a2d7ea',
            onTertiary: '#003542',
            tertiaryContainer: '#87bbce',
            onTertiaryContainer: '#0f4c5b',
            error: '#ffb4ab',
            onError: '#690005',
            errorContainer: '#93000a',
            onErrorContainer: '#ffdad6',
            primaryFixed: '#ffe088',
            primaryFixedDim: '#e9c349',
            onPrimaryFixed: '#241a00',
            onPrimaryFixedVariant: '#574500',
            secondaryFixed: '#86f7ce',
            secondaryFixedDim: '#68dbb3',
            onSecondaryFixed: '#002116',
            onSecondaryFixedVariant: '#00513d',
            tertiaryFixed: '#b6ebfe',
            tertiaryFixedDim: '#9acee1',
            onTertiaryFixed: '#001f28',
            onTertiaryFixedVariant: '#124d5d',
            background: '#0a141f',
            onBackground: '#d9e3f3',
            surfaceVariant: '#2c3642',
        },
        midnight: {
            surface: '#101726',
            surfaceDim: '#0a0f1a',
            surfaceBright: '#27354d',
            surfaceContainerLowest: '#0a0f1a',
            surfaceContainerLow: '#0d131e',
            surfaceContainer: '#1a2333',
            surfaceContainerHigh: '#212c40',
            surfaceContainerHighest: '#27354d',
            onSurface: '#f5f5f7',
            onSurfaceVariant: '#a0aab2',
            inverseSurface: '#f5f5f7',
            inverseOnSurface: '#1a2333',
            outline: '#7c8a99',
            outlineVariant: '#35465c',
            surfaceTint: '#d4af37',
            primary: '#1e5631',
            onPrimary: '#ffffff',
            primaryContainer: '#133d21',
            onPrimaryContainer: '#80c497',
            inversePrimary: '#80c497',
            secondary: '#d4af37',
            onSecondary: '#101726',
            secondaryContainer: '#9c8127',
            onSecondaryContainer: '#f5e8b8',
            tertiary: '#417e94',
            onTertiary: '#ffffff',
            tertiaryContainer: '#2c586b',
            onTertiaryContainer: '#b5dbe8',
            error: '#ffb4ab',
            onError: '#690005',
            errorContainer: '#93000a',
            onErrorContainer: '#ffdad6',
            primaryFixed: '#80c497',
            primaryFixedDim: '#1e5631',
            onPrimaryFixed: '#002116',
            onPrimaryFixedVariant: '#00513d',
            secondaryFixed: '#f5e8b8',
            secondaryFixedDim: '#d4af37',
            onSecondaryFixed: '#2a2200',
            onSecondaryFixedVariant: '#574500',
            tertiaryFixed: '#b5dbe8',
            tertiaryFixedDim: '#417e94',
            onTertiaryFixed: '#001f28',
            onTertiaryFixedVariant: '#124d5d',
            background: '#101726',
            onBackground: '#f5f5f7',
            surfaceVariant: '#27354d',
        }
    }
};

export default colors;
